// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `DataInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __D__NVPACK_tum_teambots_Windows_TeambotLogIceServer_TeambotLogIceServer_DataInterface_h__
#define __D__NVPACK_tum_teambots_Windows_TeambotLogIceServer_TeambotLogIceServer_DataInterface_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Communication
{

class Data;

class DataInterface;

}

}

namespace Communication
{

class Data;
bool operator==(const Data&, const Data&);
bool operator<(const Data&, const Data&);

class DataInterface;
bool operator==(const DataInterface&, const DataInterface&);
bool operator<(const DataInterface&, const DataInterface&);

}

namespace IceInternal
{

::Ice::Object* upCast(::Communication::Data*);
::IceProxy::Ice::Object* upCast(::IceProxy::Communication::Data*);

::Ice::Object* upCast(::Communication::DataInterface*);
::IceProxy::Ice::Object* upCast(::IceProxy::Communication::DataInterface*);

}

namespace Communication
{

typedef ::IceInternal::Handle< ::Communication::Data> DataPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Communication::Data> DataPrx;

void __read(::IceInternal::BasicStream*, DataPrx&);
void __patch__DataPtr(void*, ::Ice::ObjectPtr&);

typedef ::IceInternal::Handle< ::Communication::DataInterface> DataInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Communication::DataInterface> DataInterfacePrx;

void __read(::IceInternal::BasicStream*, DataInterfacePrx&);
void __patch__DataInterfacePtr(void*, ::Ice::ObjectPtr&);

}

namespace Communication
{

enum DataTypeIce
{
    PICTURE,
    DEBUG,
    INFO,
    LOGGERINFO,
    ACCELEROMETER,
    GYROSCOPE,
    UNSPECIFIED
};

void __write(::IceInternal::BasicStream*, DataTypeIce);
void __read(::IceInternal::BasicStream*, DataTypeIce&);

typedef ::std::vector< ::Ice::Byte> dataSequence;

}

namespace Communication
{

class Callback_DataInterface_sendData_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_DataInterface_sendData_Base> Callback_DataInterface_sendDataPtr;

}

namespace IceProxy
{

namespace Communication
{

class Data : virtual public ::IceProxy::Ice::Object
{
public:
    
    ::IceInternal::ProxyHandle<Data> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Data> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Data*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<Data*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

class DataInterface : virtual public ::IceProxy::Ice::Object
{
public:

    void sendData(const ::Communication::DataPtr& dataObject)
    {
        sendData(dataObject, 0);
    }
    void sendData(const ::Communication::DataPtr& dataObject, const ::Ice::Context& __ctx)
    {
        sendData(dataObject, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr& dataObject)
    {
        return begin_sendData(dataObject, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr& dataObject, const ::Ice::Context& __ctx)
    {
        return begin_sendData(dataObject, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr& dataObject, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendData(dataObject, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr& dataObject, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendData(dataObject, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr& dataObject, const ::Communication::Callback_DataInterface_sendDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendData(dataObject, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr& dataObject, const ::Ice::Context& __ctx, const ::Communication::Callback_DataInterface_sendDataPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sendData(dataObject, &__ctx, __del, __cookie);
    }

    void end_sendData(const ::Ice::AsyncResultPtr&);
    
private:

    void sendData(const ::Communication::DataPtr&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sendData(const ::Communication::DataPtr&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<DataInterface> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<DataInterface> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<DataInterface*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<DataInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Communication
{

class Data : virtual public ::IceDelegate::Ice::Object
{
public:
};

class DataInterface : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void sendData(const ::Communication::DataPtr&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace Communication
{

class Data : virtual public ::IceDelegate::Communication::Data,
             virtual public ::IceDelegateM::Ice::Object
{
public:
};

class DataInterface : virtual public ::IceDelegate::Communication::DataInterface,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void sendData(const ::Communication::DataPtr&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace Communication
{

class Data : virtual public ::IceDelegate::Communication::Data,
             virtual public ::IceDelegateD::Ice::Object
{
public:
};

class DataInterface : virtual public ::IceDelegate::Communication::DataInterface,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void sendData(const ::Communication::DataPtr&, const ::Ice::Context*);
};

}

}

namespace Communication
{

class Data : virtual public ::Ice::Object
{
public:

    typedef DataPrx ProxyType;
    typedef DataPtr PointerType;
    
    Data() {}
    Data(::Communication::DataTypeIce, ::Ice::Long, const ::Communication::dataSequence&);
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();


    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif

    static const ::Ice::ObjectFactoryPtr& ice_factory();

protected:

    virtual ~Data() {}

    friend class Data__staticInit;

public:

    ::Communication::DataTypeIce type;

    ::Ice::Long timeStamp;

    ::Communication::dataSequence byteArrayData;
};

class Data__staticInit
{
public:

    ::Communication::Data _init;
};

static Data__staticInit _Data_init;

inline bool operator==(const Data& l, const Data& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Data& l, const Data& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

class DataInterface : virtual public ::Ice::Object
{
public:

    typedef DataInterfacePrx ProxyType;
    typedef DataInterfacePtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void sendData(const ::Communication::DataPtr&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sendData(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const DataInterface& l, const DataInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const DataInterface& l, const DataInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Communication
{

template<class T>
class CallbackNC_DataInterface_sendData : public Callback_DataInterface_sendData_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_DataInterface_sendData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DataInterface_sendData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DataInterface_sendData<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DataInterface_sendData<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_DataInterface_sendData<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_DataInterface_sendData : public Callback_DataInterface_sendData_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_DataInterface_sendData(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DataInterface_sendData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DataInterface_sendData<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DataInterface_sendData<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_DataInterface_sendDataPtr
newCallback_DataInterface_sendData(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_DataInterface_sendData<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
