// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `MessageInterface.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <MessageInterface.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/DisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __Communication__MessageInterface__fetchData_name = "fetchData";

static const ::std::string __Communication__MessageInterface__sendData_name = "sendData";

::Ice::Object* IceInternal::upCast(::Communication::MessageInterface* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::Communication::MessageInterface* p) { return p; }

void
Communication::__read(::IceInternal::BasicStream* __is, ::Communication::MessageInterfacePrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Communication::MessageInterface;
        v->__copyFrom(proxy);
    }
}

::Communication::dataSequence
IceProxy::Communication::MessageInterface::fetchData(const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Communication__MessageInterface__fetchData_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Communication::MessageInterface* __del = dynamic_cast< ::IceDelegate::Communication::MessageInterface*>(__delBase.get());
            return __del->fetchData(__ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Communication::MessageInterface::begin_fetchData(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Communication__MessageInterface__fetchData_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Communication__MessageInterface__fetchData_name, __del, __cookie);
    try
    {
        __result->__prepare(__Communication__MessageInterface__fetchData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Communication::dataSequence
IceProxy::Communication::MessageInterface::end_fetchData(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Communication__MessageInterface__fetchData_name);
    ::Communication::dataSequence __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

void
IceProxy::Communication::MessageInterface::sendData(const ::Communication::dataSequence& a, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Communication::MessageInterface* __del = dynamic_cast< ::IceDelegate::Communication::MessageInterface*>(__delBase.get());
            __del->sendData(a, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Communication::MessageInterface::begin_sendData(const ::Communication::dataSequence& a, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Communication__MessageInterface__sendData_name, __del, __cookie);
    try
    {
        __result->__prepare(__Communication__MessageInterface__sendData_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        if(a.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&a[0], &a[0] + a.size());
        }
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Communication::MessageInterface::end_sendData(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Communication__MessageInterface__sendData_name);
}

const ::std::string&
IceProxy::Communication::MessageInterface::ice_staticId()
{
    return ::Communication::MessageInterface::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Communication::MessageInterface::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Communication::MessageInterface);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Communication::MessageInterface::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Communication::MessageInterface);
}

::IceProxy::Ice::Object*
IceProxy::Communication::MessageInterface::__newInstance() const
{
    return new MessageInterface;
}

::Communication::dataSequence
IceDelegateM::Communication::MessageInterface::fetchData(const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Communication__MessageInterface__fetchData_name, ::Ice::Normal, __context);
    bool __ok = __og.invoke();
    ::Communication::dataSequence __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::Communication::MessageInterface::sendData(const ::Communication::dataSequence& a, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Communication__MessageInterface__sendData_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        if(a.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&a[0], &a[0] + a.size());
        }
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::Communication::dataSequence
IceDelegateD::Communication::MessageInterface::fetchData(const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Communication::dataSequence& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Communication::MessageInterface* servant = dynamic_cast< ::Communication::MessageInterface*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->fetchData(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Communication::dataSequence& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Communication__MessageInterface__fetchData_name, ::Ice::Normal, __context);
    ::Communication::dataSequence __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::Communication::MessageInterface::sendData(const ::Communication::dataSequence& a, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Communication::dataSequence& a, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_a(a)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Communication::MessageInterface* servant = dynamic_cast< ::Communication::MessageInterface*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->sendData(_m_a, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Communication::dataSequence& _m_a;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Communication__MessageInterface__sendData_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(a, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
Communication::MessageInterface::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __Communication__MessageInterface_ids[2] =
{
    "::Communication::MessageInterface",
    "::Ice::Object"
};

bool
Communication::MessageInterface::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Communication__MessageInterface_ids, __Communication__MessageInterface_ids + 2, _s);
}

::std::vector< ::std::string>
Communication::MessageInterface::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Communication__MessageInterface_ids[0], &__Communication__MessageInterface_ids[2]);
}

const ::std::string&
Communication::MessageInterface::ice_id(const ::Ice::Current&) const
{
    return __Communication__MessageInterface_ids[0];
}

const ::std::string&
Communication::MessageInterface::ice_staticId()
{
    return __Communication__MessageInterface_ids[0];
}

::Ice::DispatchStatus
Communication::MessageInterface::___fetchData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.is()->skipEmptyEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::Communication::dataSequence __ret = fetchData(__current);
    if(__ret.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&__ret[0], &__ret[0] + __ret.size());
    }
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Communication::MessageInterface::___sendData(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Communication::dataSequence a;
    __is->read(a);
    __is->endReadEncaps();
    sendData(a, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __Communication__MessageInterface_all[] =
{
    "fetchData",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sendData"
};

::Ice::DispatchStatus
Communication::MessageInterface::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__Communication__MessageInterface_all, __Communication__MessageInterface_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Communication__MessageInterface_all)
    {
        case 0:
        {
            return ___fetchData(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___sendData(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Communication::MessageInterface::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
Communication::MessageInterface::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
Communication::MessageInterface::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Communication::MessageInterface was not generated with stream support";
    throw ex;
}

void
Communication::MessageInterface::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Communication::MessageInterface was not generated with stream support";
    throw ex;
}
#endif

void 
Communication::__patch__MessageInterfacePtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::Communication::MessageInterfacePtr* p = static_cast< ::Communication::MessageInterfacePtr*>(__addr);
    assert(p);
    *p = ::Communication::MessageInterfacePtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::Communication::MessageInterface::ice_staticId(), v->ice_id());
    }
}
