// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `IData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;
using _Microsoft = global::Microsoft;

#pragma warning disable 1591

namespace teambot
{
    namespace communication
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class TBFrame : Ice.ObjectImpl
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte Id;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte SubId;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short TimeStamp;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBFrame()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBFrame(byte Id, byte SubId, short TimeStamp)
            {
                this.Id = Id;
                this.SubId = SubId;
                this.TimeStamp = TimeStamp;
            }

            #endregion

            #region Slice type-related members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame"
            };

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids()
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id()
            {
                return ids__[1];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id(Ice.Current current__)
            {
                return ids__[1];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new string ice_staticId()
            {
                return ids__[1];
            }

            #endregion

            #region Operation dispatch

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.writeByte(Id);
                os__.writeByte(SubId);
                os__.writeShort(TimeStamp);
                os__.endWriteSlice();
                base.write__(os__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                Id = is__.readByte();
                SubId = is__.readByte();
                TimeStamp = is__.readShort();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBFrame was not generated with stream support";
                throw ex;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBFrame was not generated with stream support";
                throw ex;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class TBVelocity : teambot.communication.TBFrame
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte speedLeft;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte speedRight;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBVelocity() : base()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBVelocity(byte Id, byte SubId, short TimeStamp, byte speedLeft, byte speedRight) : base(Id, SubId, TimeStamp)
            {
                this.speedLeft = speedLeft;
                this.speedRight = speedRight;
            }

            #endregion

            #region Slice type-related members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBVelocity"
            };

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids()
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id()
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id(Ice.Current current__)
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Operation dispatch

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.writeByte(speedLeft);
                os__.writeByte(speedRight);
                os__.endWriteSlice();
                base.write__(os__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                speedLeft = is__.readByte();
                speedRight = is__.readByte();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBVelocity was not generated with stream support";
                throw ex;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBVelocity was not generated with stream support";
                throw ex;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class TBPosition : teambot.communication.TBFrame
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short distance;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBPosition() : base()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBPosition(byte Id, byte SubId, short TimeStamp, short distance) : base(Id, SubId, TimeStamp)
            {
                this.distance = distance;
            }

            #endregion

            #region Slice type-related members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBPosition"
            };

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids()
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id()
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id(Ice.Current current__)
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Operation dispatch

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.writeShort(distance);
                os__.endWriteSlice();
                base.write__(os__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                distance = is__.readShort();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBPosition was not generated with stream support";
                throw ex;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBPosition was not generated with stream support";
                throw ex;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class TBInfraredData : teambot.communication.TBFrame
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte leftDistance;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte middleDistance;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public byte rightDistance;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBInfraredData() : base()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBInfraredData(byte Id, byte SubId, short TimeStamp, byte leftDistance, byte middleDistance, byte rightDistance) : base(Id, SubId, TimeStamp)
            {
                this.leftDistance = leftDistance;
                this.middleDistance = middleDistance;
                this.rightDistance = rightDistance;
            }

            #endregion

            #region Slice type-related members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBInfraredData"
            };

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids()
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id()
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id(Ice.Current current__)
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Operation dispatch

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.writeByte(leftDistance);
                os__.writeByte(middleDistance);
                os__.writeByte(rightDistance);
                os__.endWriteSlice();
                base.write__(os__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                leftDistance = is__.readByte();
                middleDistance = is__.readByte();
                rightDistance = is__.readByte();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBInfraredData was not generated with stream support";
                throw ex;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBInfraredData was not generated with stream support";
                throw ex;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class TBPositionData : teambot.communication.TBFrame
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short x;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short y;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short angle;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBPositionData() : base()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBPositionData(byte Id, byte SubId, short TimeStamp, short x, short y, short angle) : base(Id, SubId, TimeStamp)
            {
                this.x = x;
                this.y = y;
                this.angle = angle;
            }

            #endregion

            #region Slice type-related members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBPositionData"
            };

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids()
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id()
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id(Ice.Current current__)
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Operation dispatch

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.writeShort(x);
                os__.writeShort(y);
                os__.writeShort(angle);
                os__.endWriteSlice();
                base.write__(os__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                x = is__.readShort();
                y = is__.readShort();
                angle = is__.readShort();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBPositionData was not generated with stream support";
                throw ex;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBPositionData was not generated with stream support";
                throw ex;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial class TBPositionReached : teambot.communication.TBFrame
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short x;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short y;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public short angle;

            #endregion

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBPositionReached() : base()
            {
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public TBPositionReached(byte Id, byte SubId, short TimeStamp, short x, short y, short angle) : base(Id, SubId, TimeStamp)
            {
                this.x = x;
                this.y = y;
                this.angle = angle;
            }

            #endregion

            #region Slice type-related members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBPositionReached"
            };

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids()
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id()
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override string ice_id(Ice.Current current__)
            {
                return ids__[2];
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public static new string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Operation dispatch

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.writeShort(x);
                os__.writeShort(y);
                os__.writeShort(angle);
                os__.endWriteSlice();
                base.write__(os__);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                x = is__.readShort();
                y = is__.readShort();
                angle = is__.readShort();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBPositionReached was not generated with stream support";
                throw ex;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::TBPositionReached was not generated with stream support";
                throw ex;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial interface IData : Ice.Object, IDataOperations_, IDataOperationsNC_
        {
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public delegate void Callback_IData_receive();
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBFramePrx : Ice.ObjectPrx
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBVelocityPrx : teambot.communication.TBFramePrx
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBPositionPrx : teambot.communication.TBFramePrx
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBInfraredDataPrx : teambot.communication.TBFramePrx
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBPositionDataPrx : teambot.communication.TBFramePrx
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBPositionReachedPrx : teambot.communication.TBFramePrx
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface IDataPrx : Ice.ObjectPrx
        {
            void receive(teambot.communication.TBFrame data);
            void receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> context__);

            Ice.AsyncResult<teambot.communication.Callback_IData_receive> begin_receive(teambot.communication.TBFrame data);
            Ice.AsyncResult<teambot.communication.Callback_IData_receive> begin_receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> ctx__);

            Ice.AsyncResult begin_receive(teambot.communication.TBFrame data, Ice.AsyncCallback cb__, object cookie__);
            Ice.AsyncResult begin_receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__);

            void end_receive(Ice.AsyncResult r__);
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface IDataOperations_
        {
            void receive(teambot.communication.TBFrame data, Ice.Current current__);
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface IDataOperationsNC_
        {
            void receive(teambot.communication.TBFrame data);
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBFramePrxHelper : Ice.ObjectPrxHelperBase, TBFramePrx
        {
            #region Asynchronous operations

            #endregion

            #region Checked and unchecked cast operations

            public static TBFramePrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBFramePrx r = b as TBFramePrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    TBFramePrxHelper h = new TBFramePrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBFramePrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                TBFramePrx r = b as TBFramePrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    TBFramePrxHelper h = new TBFramePrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBFramePrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        TBFramePrxHelper h = new TBFramePrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBFramePrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        TBFramePrxHelper h = new TBFramePrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBFramePrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBFramePrx r = b as TBFramePrx;
                if(r == null)
                {
                    TBFramePrxHelper h = new TBFramePrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBFramePrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                TBFramePrxHelper h = new TBFramePrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame"
            };

            public static string ice_staticId()
            {
                return ids__[1];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new TBFrameDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new TBFrameDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, TBFramePrx v__)
            {
                os__.writeProxy(v__);
            }

            public static TBFramePrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    TBFramePrxHelper result = new TBFramePrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBVelocityPrxHelper : Ice.ObjectPrxHelperBase, TBVelocityPrx
        {
            #region Asynchronous operations

            #endregion

            #region Checked and unchecked cast operations

            public static TBVelocityPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBVelocityPrx r = b as TBVelocityPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    TBVelocityPrxHelper h = new TBVelocityPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBVelocityPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                TBVelocityPrx r = b as TBVelocityPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    TBVelocityPrxHelper h = new TBVelocityPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBVelocityPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        TBVelocityPrxHelper h = new TBVelocityPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBVelocityPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        TBVelocityPrxHelper h = new TBVelocityPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBVelocityPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBVelocityPrx r = b as TBVelocityPrx;
                if(r == null)
                {
                    TBVelocityPrxHelper h = new TBVelocityPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBVelocityPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                TBVelocityPrxHelper h = new TBVelocityPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBVelocity"
            };

            public static string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new TBVelocityDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new TBVelocityDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, TBVelocityPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static TBVelocityPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    TBVelocityPrxHelper result = new TBVelocityPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionPrxHelper : Ice.ObjectPrxHelperBase, TBPositionPrx
        {
            #region Asynchronous operations

            #endregion

            #region Checked and unchecked cast operations

            public static TBPositionPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionPrx r = b as TBPositionPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    TBPositionPrxHelper h = new TBPositionPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionPrx r = b as TBPositionPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    TBPositionPrxHelper h = new TBPositionPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        TBPositionPrxHelper h = new TBPositionPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBPositionPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        TBPositionPrxHelper h = new TBPositionPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBPositionPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionPrx r = b as TBPositionPrx;
                if(r == null)
                {
                    TBPositionPrxHelper h = new TBPositionPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                TBPositionPrxHelper h = new TBPositionPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBPosition"
            };

            public static string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new TBPositionDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new TBPositionDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, TBPositionPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static TBPositionPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    TBPositionPrxHelper result = new TBPositionPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBInfraredDataPrxHelper : Ice.ObjectPrxHelperBase, TBInfraredDataPrx
        {
            #region Asynchronous operations

            #endregion

            #region Checked and unchecked cast operations

            public static TBInfraredDataPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBInfraredDataPrx r = b as TBInfraredDataPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    TBInfraredDataPrxHelper h = new TBInfraredDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBInfraredDataPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                TBInfraredDataPrx r = b as TBInfraredDataPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    TBInfraredDataPrxHelper h = new TBInfraredDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBInfraredDataPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        TBInfraredDataPrxHelper h = new TBInfraredDataPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBInfraredDataPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        TBInfraredDataPrxHelper h = new TBInfraredDataPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBInfraredDataPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBInfraredDataPrx r = b as TBInfraredDataPrx;
                if(r == null)
                {
                    TBInfraredDataPrxHelper h = new TBInfraredDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBInfraredDataPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                TBInfraredDataPrxHelper h = new TBInfraredDataPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBInfraredData"
            };

            public static string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new TBInfraredDataDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new TBInfraredDataDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, TBInfraredDataPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static TBInfraredDataPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    TBInfraredDataPrxHelper result = new TBInfraredDataPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionDataPrxHelper : Ice.ObjectPrxHelperBase, TBPositionDataPrx
        {
            #region Asynchronous operations

            #endregion

            #region Checked and unchecked cast operations

            public static TBPositionDataPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionDataPrx r = b as TBPositionDataPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    TBPositionDataPrxHelper h = new TBPositionDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionDataPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionDataPrx r = b as TBPositionDataPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    TBPositionDataPrxHelper h = new TBPositionDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionDataPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        TBPositionDataPrxHelper h = new TBPositionDataPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBPositionDataPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        TBPositionDataPrxHelper h = new TBPositionDataPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBPositionDataPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionDataPrx r = b as TBPositionDataPrx;
                if(r == null)
                {
                    TBPositionDataPrxHelper h = new TBPositionDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionDataPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                TBPositionDataPrxHelper h = new TBPositionDataPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBPositionData"
            };

            public static string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new TBPositionDataDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new TBPositionDataDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, TBPositionDataPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static TBPositionDataPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    TBPositionDataPrxHelper result = new TBPositionDataPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionReachedPrxHelper : Ice.ObjectPrxHelperBase, TBPositionReachedPrx
        {
            #region Asynchronous operations

            #endregion

            #region Checked and unchecked cast operations

            public static TBPositionReachedPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionReachedPrx r = b as TBPositionReachedPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    TBPositionReachedPrxHelper h = new TBPositionReachedPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionReachedPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionReachedPrx r = b as TBPositionReachedPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    TBPositionReachedPrxHelper h = new TBPositionReachedPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionReachedPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        TBPositionReachedPrxHelper h = new TBPositionReachedPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBPositionReachedPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        TBPositionReachedPrxHelper h = new TBPositionReachedPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static TBPositionReachedPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                TBPositionReachedPrx r = b as TBPositionReachedPrx;
                if(r == null)
                {
                    TBPositionReachedPrxHelper h = new TBPositionReachedPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static TBPositionReachedPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                TBPositionReachedPrxHelper h = new TBPositionReachedPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::TBFrame",
                "::teambot::communication::TBPositionReached"
            };

            public static string ice_staticId()
            {
                return ids__[2];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new TBPositionReachedDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new TBPositionReachedDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, TBPositionReachedPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static TBPositionReachedPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    TBPositionReachedPrxHelper result = new TBPositionReachedPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class IDataPrxHelper : Ice.ObjectPrxHelperBase, IDataPrx
        {
            #region Synchronous operations

            public void receive(teambot.communication.TBFrame data)
            {
                receive(data, null, false);
            }

            public void receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> context__)
            {
                receive(data, context__, true);
            }

            private void receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> context__, bool explicitContext__)
            {
                if(explicitContext__ && context__ == null)
                {
                    context__ = emptyContext_;
                }
                int cnt__ = 0;
                while(true)
                {
                    Ice.ObjectDel_ delBase__ = null;
                    try
                    {
                        delBase__ = getDelegate__(false);
                        IDataDel_ del__ = (IDataDel_)delBase__;
                        del__.receive(data, context__);
                        return;
                    }
                    catch(IceInternal.LocalExceptionWrapper ex__)
                    {
                        handleExceptionWrapper__(delBase__, ex__);
                    }
                    catch(Ice.LocalException ex__)
                    {
                        handleException__(delBase__, ex__, true, ref cnt__);
                    }
                }
            }

            #endregion

            #region Asynchronous operations

            public Ice.AsyncResult<teambot.communication.Callback_IData_receive> begin_receive(teambot.communication.TBFrame data)
            {
                return begin_receive(data, null, false, null, null);
            }

            public Ice.AsyncResult<teambot.communication.Callback_IData_receive> begin_receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> ctx__)
            {
                return begin_receive(data, ctx__, true, null, null);
            }

            public Ice.AsyncResult begin_receive(teambot.communication.TBFrame data, Ice.AsyncCallback cb__, object cookie__)
            {
                return begin_receive(data, null, false, cb__, cookie__);
            }

            public Ice.AsyncResult begin_receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> ctx__, Ice.AsyncCallback cb__, object cookie__)
            {
                return begin_receive(data, ctx__, true, cb__, cookie__);
            }

            private const string __receive_name = "receive";

            public void end_receive(Ice.AsyncResult r__)
            {
                end__(r__, __receive_name);
            }

            private Ice.AsyncResult<teambot.communication.Callback_IData_receive> begin_receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> ctx__, bool explicitContext__, Ice.AsyncCallback cb__, object cookie__)
            {
                IceInternal.OnewayOutgoingAsync<teambot.communication.Callback_IData_receive> result__ = new IceInternal.OnewayOutgoingAsync<teambot.communication.Callback_IData_receive>(this, __receive_name, receive_completed__, cookie__);
                if(cb__ != null)
                {
                    result__.whenCompletedWithAsyncCallback(cb__);
                }
                try
                {
                    result__.prepare__(__receive_name, Ice.OperationMode.Normal, ctx__, explicitContext__);
                    IceInternal.BasicStream os__ = result__.ostr__;
                    os__.writeObject(data);
                    os__.writePendingObjects();
                    os__.endWriteEncaps();
                    result__.send__(true);
                }
                catch(Ice.LocalException ex__)
                {
                    result__.exceptionAsync__(ex__);
                }
                return result__;
            }

            private void receive_completed__(teambot.communication.Callback_IData_receive cb__)
            {
                if(cb__ != null)
                {
                    cb__();
                }
            }

            #endregion

            #region Checked and unchecked cast operations

            public static IDataPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                IDataPrx r = b as IDataPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    IDataPrxHelper h = new IDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static IDataPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                IDataPrx r = b as IDataPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    IDataPrxHelper h = new IDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static IDataPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        IDataPrxHelper h = new IDataPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static IDataPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        IDataPrxHelper h = new IDataPrxHelper();
                        h.copyFrom__(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static IDataPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                IDataPrx r = b as IDataPrx;
                if(r == null)
                {
                    IDataPrxHelper h = new IDataPrxHelper();
                    h.copyFrom__(b);
                    r = h;
                }
                return r;
            }

            public static IDataPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                IDataPrxHelper h = new IDataPrxHelper();
                h.copyFrom__(bb);
                return h;
            }

            public static readonly string[] ids__ =
            {
                "::Ice::Object",
                "::teambot::communication::IData"
            };

            public static string ice_staticId()
            {
                return ids__[1];
            }

            #endregion

            #region Marshaling support

            protected override Ice.ObjectDelM_ createDelegateM__()
            {
                return new IDataDelM_();
            }

            protected override Ice.ObjectDelD_ createDelegateD__()
            {
                return new IDataDelD_();
            }

            public static void write__(IceInternal.BasicStream os__, IDataPrx v__)
            {
                os__.writeProxy(v__);
            }

            public static IDataPrx read__(IceInternal.BasicStream is__)
            {
                Ice.ObjectPrx proxy = is__.readProxy();
                if(proxy != null)
                {
                    IDataPrxHelper result = new IDataPrxHelper();
                    result.copyFrom__(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBFrameDel_ : Ice.ObjectDel_
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBVelocityDel_ : teambot.communication.TBFrameDel_
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBPositionDel_ : teambot.communication.TBFrameDel_
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBInfraredDataDel_ : teambot.communication.TBFrameDel_
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBPositionDataDel_ : teambot.communication.TBFrameDel_
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface TBPositionReachedDel_ : teambot.communication.TBFrameDel_
        {
        }

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public interface IDataDel_ : Ice.ObjectDel_
        {
            void receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> context__);
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBFrameDelM_ : Ice.ObjectDelM_, TBFrameDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBVelocityDelM_ : Ice.ObjectDelM_, TBVelocityDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionDelM_ : Ice.ObjectDelM_, TBPositionDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBInfraredDataDelM_ : Ice.ObjectDelM_, TBInfraredDataDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionDataDelM_ : Ice.ObjectDelM_, TBPositionDataDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionReachedDelM_ : Ice.ObjectDelM_, TBPositionReachedDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class IDataDelM_ : Ice.ObjectDelM_, IDataDel_
        {
            public void receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> context__)
            {
                IceInternal.Outgoing og__ = handler__.getOutgoing("receive", Ice.OperationMode.Normal, context__);
                try
                {
                    try
                    {
                        IceInternal.BasicStream os__ = og__.ostr();
                        os__.writeObject(data);
                        os__.writePendingObjects();
                    }
                    catch(Ice.LocalException ex__)
                    {
                        og__.abort(ex__);
                    }
                    bool ok__ = og__.invoke();
                    if(!og__.istr().isEmpty())
                    {
                        try
                        {
                            if(!ok__)
                            {
                                try
                                {
                                    og__.throwUserException();
                                }
                                catch(Ice.UserException ex__)
                                {
                                    throw new Ice.UnknownUserException(ex__.ice_name(), ex__);
                                }
                            }
                            og__.istr().skipEmptyEncaps();
                        }
                        catch(Ice.LocalException ex__)
                        {
                            throw new IceInternal.LocalExceptionWrapper(ex__, false);
                        }
                    }
                }
                finally
                {
                    handler__.reclaimOutgoing(og__);
                }
            }
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBFrameDelD_ : Ice.ObjectDelD_, TBFrameDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBVelocityDelD_ : Ice.ObjectDelD_, TBVelocityDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionDelD_ : Ice.ObjectDelD_, TBPositionDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBInfraredDataDelD_ : Ice.ObjectDelD_, TBInfraredDataDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionDataDelD_ : Ice.ObjectDelD_, TBPositionDataDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class TBPositionReachedDelD_ : Ice.ObjectDelD_, TBPositionReachedDel_
        {
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public sealed class IDataDelD_ : Ice.ObjectDelD_, IDataDel_
        {
            [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031")]
            public void receive(teambot.communication.TBFrame data, _System.Collections.Generic.Dictionary<string, string> context__)
            {
                Ice.Current current__ = new Ice.Current();
                initCurrent__(ref current__, "receive", Ice.OperationMode.Normal, context__);
                IceInternal.Direct.RunDelegate run__ = delegate(Ice.Object obj__)
                {
                    IData servant__ = null;
                    try
                    {
                        servant__ = (IData)obj__;
                    }
                    catch(_System.InvalidCastException)
                    {
                        throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
                    }
                    servant__.receive(data, current__);
                    return Ice.DispatchStatus.DispatchOK;
                };
                IceInternal.Direct direct__ = null;
                try
                {
                    direct__ = new IceInternal.Direct(current__, run__);
                    try
                    {
                        Ice.DispatchStatus status__ = direct__.servant().collocDispatch__(direct__);
                        _System.Diagnostics.Debug.Assert(status__ == Ice.DispatchStatus.DispatchOK);
                    }
                    finally
                    {
                        direct__.destroy();
                    }
                }
                catch(Ice.SystemException)
                {
                    throw;
                }
                catch(_System.Exception ex__)
                {
                    IceInternal.LocalExceptionWrapper.throwWrapper(ex__);
                }
            }
        }
    }
}

namespace teambot
{
    namespace communication
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.4.2")]
        public abstract class IDataDisp_ : Ice.ObjectImpl, IData
        {
            #region Slice operations

            public void receive(teambot.communication.TBFrame data)
            {
                receive(data, Ice.ObjectImpl.defaultCurrent);
            }

            public abstract void receive(teambot.communication.TBFrame data, Ice.Current current__);

            #endregion

            #region Slice type-related members

            public static new readonly string[] ids__ = 
            {
                "::Ice::Object",
                "::teambot::communication::IData"
            };

            public override bool ice_isA(string s)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            public override bool ice_isA(string s, Ice.Current current__)
            {
                return _System.Array.BinarySearch(ids__, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            public override string[] ice_ids()
            {
                return ids__;
            }

            public override string[] ice_ids(Ice.Current current__)
            {
                return ids__;
            }

            public override string ice_id()
            {
                return ids__[1];
            }

            public override string ice_id(Ice.Current current__)
            {
                return ids__[1];
            }

            public static new string ice_staticId()
            {
                return ids__[1];
            }

            #endregion

            #region Operation dispatch

            [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
            public static Ice.DispatchStatus receive___(IData obj__, IceInternal.Incoming inS__, Ice.Current current__)
            {
                checkMode__(Ice.OperationMode.Normal, current__.mode);
                IceInternal.BasicStream is__ = inS__.istr();
                is__.startReadEncaps();
                IceInternal.ParamPatcher<teambot.communication.TBFrame>data_PP = new IceInternal.ParamPatcher<teambot.communication.TBFrame>("::teambot::communication::TBFrame");
                is__.readObject(data_PP);
                is__.readPendingObjects();
                is__.endReadEncaps();
                obj__.receive((teambot.communication.TBFrame)data_PP.value, current__);
                return Ice.DispatchStatus.DispatchOK;
            }

            private static string[] all__ =
            {
                "ice_id",
                "ice_ids",
                "ice_isA",
                "ice_ping",
                "receive"
            };

            public override Ice.DispatchStatus dispatch__(IceInternal.Incoming inS__, Ice.Current current__)
            {
                int pos = _System.Array.BinarySearch(all__, current__.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
                if(pos < 0)
                {
                    throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
                }

                switch(pos)
                {
                    case 0:
                    {
                        return ice_id___(this, inS__, current__);
                    }
                    case 1:
                    {
                        return ice_ids___(this, inS__, current__);
                    }
                    case 2:
                    {
                        return ice_isA___(this, inS__, current__);
                    }
                    case 3:
                    {
                        return ice_ping___(this, inS__, current__);
                    }
                    case 4:
                    {
                        return receive___(this, inS__, current__);
                    }
                }

                _System.Diagnostics.Debug.Assert(false);
                throw new Ice.OperationNotExistException(current__.id, current__.facet, current__.operation);
            }

            #endregion

            #region Marshaling support

            public override void write__(IceInternal.BasicStream os__)
            {
                os__.writeTypeId(ice_staticId());
                os__.startWriteSlice();
                os__.endWriteSlice();
                base.write__(os__);
            }

            public override void read__(IceInternal.BasicStream is__, bool rid__)
            {
                if(rid__)
                {
                    /* string myId = */ is__.readTypeId();
                }
                is__.startReadSlice();
                is__.endReadSlice();
                base.read__(is__, true);
            }

            public override void write__(Ice.OutputStream outS__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::IData was not generated with stream support";
                throw ex;
            }

            public override void read__(Ice.InputStream inS__, bool rid__)
            {
                Ice.MarshalException ex = new Ice.MarshalException();
                ex.reason = "type teambot::communication::IData was not generated with stream support";
                throw ex;
            }

            #endregion
        }
    }
}
